### ISSUE TITLE
maskNC sh: 1: cdo: not found

### ISSUE THREAD

**Issue by PGZikalala** [RS-eco/processNC#1]
>> CAmask <- maskNC(file=file, ext=c(-124.482, -114.1312, 32.52884, 42.00951), outfile=outfiles)
sh: 1: cdo: not found
Created file CA_.nc.
Warning message:
In system(cdoCmd) : error in running command

do you have any suggestions on how I can address this error? Thank you in advance for your time and consideration.

**Comment by RS-eco** [comment]
Are you using a Windows computer? maskNC as well as mergeNC and aggregateNC only work on a Linux computer, which has the cdo software installed. Try using the subsetNC function if you are using a Windows computer (this is unfortunately much slower) or install cdo with sudo apt-get install cdo.

**Comment by PGZikalala** [comment]
Will do. Thank you very much.

**Comment by priyapatel1** [comment]
I got the same error on my Macbook - how can I address this issue?

Also - what is the extent variable referring to? My netcdf has separate variables for lat and lon, so how does the function know what to refer to?

**Comment by RS-eco** [comment]
@priyapatel1, as mentioned before you need to have the CDO software installed. I am afraid that CDO is probably not running on Mac and as I am not an experienced Mac-User I have not catered for this specific demand.

Regarding the extent variable, this is taking over from the raster package, so it usually comes in the format of min-long, max-long, min-lat, max-lat.
