### ISSUE TITLE
No file produced with maskNC/cropNC

### ISSUE THREAD

**Issue by jgiovando** [RS-eco/processNC#2]
I have a fully specified path for the output file (including file name and extension) and the function runs without error.  However no netCDF file is produced. Is there something else that I'm missing in the function?

**Comment by RS-eco** [comment]
Could you please post an example of your code?
And do the examples in the function documentation work for you?
These functions run CDO in the background, have you CDO installed? I believe the functions right now only work on Linux, and not on Windows or Mac.

**Comment by RS-eco** [comment]
Alternatively you might want to try out the subsetNC() function, this one only depends on the raster/terra package, but is considerably slower for large NetCDF files.

**Comment by jgiovando** [comment]
The example code does not run for me.  I'm using a Windows machine so perhaps that's the issue.  I will attempt the subsetNC function to see if that works.
