### ISSUE TITLE
Problem with package installation

### ISSUE THREAD

**Issue by Konstantinos82** [RS-eco/processNC#4]
Hello,

I' tried to install the package but I receive the following error:

√  checking for file 'C:\Users\konst\AppData\Local\Temp\RtmpwtBpsi\remotes5544760b3e9b\RS-eco-processNC-6308b7e/DESCRIPTION' ... 
-  preparing 'processNC':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'processNC_0.0.1.tar.gz'
   
* installing *source* package 'processNC' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'rlang' 0.4.11 is already loaded, but >= 1.0.2 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'processNC'
* removing 'C:/Program Files/R/R-4.1.0/library/processNC'

I've searched for solution on the internet but I can't solve it.

Kind regards

**Comment by RS-eco** [comment]
Seems like you have a very old version of the rlang package. Maybe try to update your R-packages and if that does not solve it, try to install a more recent version of R.
