### ISSUE TITLE
Error subsetNC NetCDF file 

### ISSUE THREAD

**Issue by suraj500** [RS-eco/processNC#5]
I can work on the example given by you using subsetNC. But I can not work with my own NetCDF files. I get the following error.

Error in if ((mode(varid) != "character") && (class(varid) != "ncvar4") &&  : 
  missing value where TRUE/FALSE needed

Is this issue related to the compatibility of NetCDF libraries, and how can I solve it?

**Comment by RS-eco** [comment]
Do you have the ncdf4 package installed? If it is still relevant, you can send me your file(s) and the code you are using and I will try to solve the error.
