### ISSUE TITLE
Problems with installation of package

### ISSUE THREAD

**Issue by Gonzalo1985** [RS-eco/processNC#6]
Hello,

I am writing because of a problem with the installation of package. When I get this message:

Downloading GitHub repo RS-eco/processNC@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                             
2: CRAN packages only              
3: None                            
4: terra  (1.5-21 -> 1.6-17) [CRAN]
5: raster (3.5-15 -> 3.6-3 ) [CRAN]

I choose 3: None because I am having some problems with versions of terra and raster and then I get:

Running `R CMD build`...
* checking for file ‘/data/tmp/RtmpibLVr5/remotes428b2a0ac9f3/RS-eco-processNC-f285e45/DESCRIPTION’ ... OK
* preparing ‘processNC’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘processNC_0.0.1.tar.gz’
Installing package into ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
ERROR: this R is version 3.6.3, package 'processNC' requires R >= 4.0
Warning message:
In i.p(...) :
  installation of package ‘/tmp/RtmpibLVr5/file428b2a5a5776/processNC_0.0.1.tar.gz’ had non-zero exit status

Do you know what can I do to solve this problem?

Thank you very much

Kind regards,
Gonzalo

**Comment by RS-eco** [comment]
Looks like you are currently using R version 3.6.3, while processNC depends on R version 4.0 or higher. I would recommend upgrading your R version and then trying again to install the package.

**Comment by Gonzalo1985** [comment]
Hello,

The strange thing is that I used to use this package in a R 3.4.4, so it should be working in R 3.6.3 but I am not sure why is not working.

Thank you!

**Comment by RS-eco** [comment]
Hello Gonzalo,

the package might have worked in the past with an earlier version of R, as I have changed some parts of it recently and as a consequence changed the installation dependencies to R version >= 4.0 due to some of the corresponding packages, i.e. terra, which I believe are not available for earlier versions of R. I have now re-changed the dependencies back, so you should be able to install it with R version 3.6.3. Let me know if you succeed now.

Thanks

**Comment by Gonzalo1985** [comment]
RS-eco,

Thank you! I've tried but I got this:

Installing package into ‘/data/R-libs/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
Warning message:
package ‘RS-eco’ is not available (for R version 3.6.3)

It is still not working for 3.6.3 R version.

**Comment by Gonzalo1985** [comment]
I am not sure what is the name of the package, I also tried with "processNC" but I get the same message.

**Comment by RS-eco** [comment]
Hey Gonzalo,

can you please provide the code you are using to install the package and the resulting error message you get.
I have no problems installing it, when doing:
```{r}
remotes::install_github("RS-eco/processNC")
```

**Comment by Gonzalo1985** [comment]
Hello RS-eco,

Ohh ok, I was not writing right the complete command. Now yes, it worked!

Thank you very much!

Gonzalo
