### ISSUE TITLE
README is not correct

### ISSUE THREAD

**Issue by rhijmans** [RS-eco/processNC#7]
The README states that 

> Small NetCDF files can easily be loaded into R using the raster() function from the raster package or nowadays also using the rast() function from the terra package in R, given that the ncdf4 package is installed. However, using this approach the entire file is read into memory and so memory limits are reached quickly when trying to load large NetCDF files.

There are probably good reasons to use processNC, but the above statement is not correct. The key design principle of both the raster and the terra package is that they work with rasters of any size. They do not attempt to read entire raster files into memory when processing the data, unless the file is small. Also, "terra" does not depend on ncdf4 for reading NetCDF files.

**Comment by RS-eco** [comment]
Thanks for pointing this out. I have now adjusted the README accordingly.
