### ISSUE TITLE
errors when trying to output the subset data to a new nc file

### ISSUE THREAD

**Issue by qyykk0520** [RS-eco/processNC#9]
Hi, 
 
I followed your example codes to subset values  of my own nc files with a shapefile boundary and managed to get a raster stack. 
However, when I tried to output the raster stack with writeNC, I got the following error message: 
Error in class(data) == list : 
comparison (==) is possible only for atomic and list types. 
 
Do you know how to deal with this?  Or is there any solutions I can output the processed data to a nc file? 
The code I used is as follow: 
```
#### subset within yrb shp 
ISIMIP_files <- list. files(path = "G:Data//ISIMIP/3a/pre/", 
pattern="*. nc", full.names=T) 
yrz_shp <- shapefile("D:/research/yangtze/Yangtze__boundary.shp") 
yrb_ras <- subsetNC(ISIMIP_files,ext = terra::vect(yrz_shp), varid = "pr") 
```

> yrb_ras
class       : SpatRaster 
dimensions  : 62, 22, 10958  (nrow, ncol, nlyr)
resolution  : 1.428638, 0.1847629  (x, y)
extent      : 90.4726, 121.9026, 24.45523, 35.91053  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs 
source      : memory 
names       :   1990-12-31,   1991-01-01,   1991-01-02,   1991-01-03,   1991-01-04,   1991-01-05, ... 
min values  : 1.927471e-18, 2.794970e-08, 8.230255e-10, 1.927471e-18, 1.927471e-18, 1.927471e-18, ... 
max values  : 3.058241e-04, 3.117412e-04, 5.332543e-04, 2.522074e-04, 5.435834e-05, 8.305814e-05, ... 
time        : 1990-12-31 to 2020-12-30 

```
#### output data to nc file 
data_yrb <- as.data.frame(rasterToPoints(stack(yrb_ras))) 
outfile <- tempfile(fileext="YRB_pr_te.nc4") 
writeNC(data=data_yrb, res=0.5, ext=c(90.4726, 121.9026, 24.45523, 35.91053), 
date=seq(as.Date("1990-12-31"), as.Date("2020-12-30"), by="day"), 
vars="pr", varunit="kg m-2 s-1", contact="ISIMIP cross-sectoral science team <info@isimip.org> <https://www.isimip.org>", 
institute="Potsdam Institute for Climate Impact Research (PIK)", filename=outfile) 
 
```
Many thanks.

**Comment by RS-eco** [comment]
Hi,

it's hard to provide you with a working solution, if you do not provide a reproducible example. :/ 

Nevertheless, I could at least fix the above mentioned error (Error in class(data) == list), please let me know if it works now or if you get another error message. 

Alternatively, you can also just save your output (yrb_ras) as a Spat Raster file with the `terra` package using the function `writeRaster()`. 

Thanks.

**Comment by qyykk0520** [comment]
Hi,
I tried the `writeNC` again but it reported new error: 
Error in R_nc4_create: Permission denied (creation mode was 4096)
Error in ncdf4::nc_create(filename, vard) : Error in nc_create!

The main problem is I need to save the data to netCDF format for my model. I tried `writeraster` and `writeCDF` with `terra` but the outputs more or less had some issues.

**Comment by RS-eco** [comment]
Hm, the "Error in nc_create!" is likely because you have already tried to write data to the output file. So if this happens, try to re-create a new outfile and write the data again:
```
outfile <- tempfile(fileext="YRB_pr_te.nc4") 
writeNC(data=data_yrb, res=0.5, ext=c(90.4726, 121.9026, 24.45523, 35.91053), 
date=seq(as.Date("1990-12-31"), as.Date("2020-12-30"), by="day"), 
vars="pr", varunit="kg m-2 s-1", contact="ISIMIP cross-sectoral science team <info@isimip.org> <https://www.isimip.org>", 
institute="Potsdam Institute for Climate Impact Research (PIK)", filename=outfile) 
```
At least it then worked for me.

If this still does not work, maybe you can try your code with the example files I use in my examples and see if that works or if you get the same error.

**Comment by qyykk0520** [comment]
Yes it worked this time and I got the output nc file with my data. Thank you so much!
